<div>
    <h2 class="text-md leading-5 font-semibold tracking-wider uppercase">Contacts</h2>
    <div>
        <ul class="mt-4">
            <li><a class="text-base ">1234 Heaven Stress, Beverly Hill.</a></li>
            <li><a class="text-base ">Telephone: +01 234 567 89</a></li>
            <li><a class="email text-base">Email:asd@ags.com</a></li>
            <li><a class="text-base ">8:00-19:00, Monday-Friday</a></li>

        </ul>
    </div>
</div>