<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<script src="https://code.jquery.com/jquery-3.6.1.slim.min.js" integrity="sha256-w8CvhFs7iHNVUtnSP0YKEg00p9Ih13rlL9zGqvLdePA=" crossorigin="anonymous"></script>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

<script src="https://kit.fontawesome.com/257ed6903e.js" crossorigin="anonymous"></script>
<div class="w-2/3 flex flex-row justify-start border-b-[1px] border-solid border-[#ebebeb]">
    <div class="w-[900px] flex flex-row text-left m-auto content-center justify-center leading-[50px]">
    <div class="flex flex-row  content-center justify-center w-5/11 px-[10px]">
    <i class="fa-sharp fa-solid fa-location-dot self-center text-[14px] text-[#5d5d5d]"></i>
    <p class="text-[14px] px-[5px] text-[#5d5d5d]">7563 St. Vicent Place, Glasgo</p>
    </div>
    <div class="6/11 px-[10px] flex flex-row content-center justify-center">
        <i class="fa-solid fa-phone self-center text-[14px] text-[#5d5d5d]"></i>
        <p class="px-[5px] text-[14px] text-[#5d5d5d]">+777 2345 7885 | +777 2345 7886</p>
    </div>
    </div>

</div>

<!-- <ul class="my-list">
    <li>1st Element</li>
    <li>2nd Element</li>
    <li>3rd Element</li>
    <li>4th Element</li>
    <li>5th Element</li>
    <li>6th Element</li>
    <li>7th Element</li>
    <li>8th Element</li>
</ul>

<script>

     $(".my-list").slick({
         dots: true,
         infinite: true,
         speed: 300,
         slidesToShow: 4,
         slidesToScroll: 1
      });
   

</script> -->